### PR TITLE
Update "tested on" badge in README to include PHP v8.3

### PR DESCRIPTION
**Pull request by fredden**
While this change is hopefully useful, the primary purpose of this pull request is to test if the recent changes to the Coveralls workflow work well with an external contributor or not.

### CODE REVIEW

**Review by jrfnl — APPROVED** [review]
Thanks @fredden for submitting this PR. Approving it for the content of the PR. Now 🤞🏻 to see if the upload to Coveralls works... ;-)

**Comment by fredden** [comment]
Sadly it looks like it's failed. :(

https://github.com/PHPCSStandards/PHPCSUtils/actions/runs/6170710161/job/16747560218?pr=514

Screenshot_2023-09-13_10-46-12

**Comment by jrfnl** [comment]
@fredden It has indeed. I've [reported back to Coveralls](https://github.com/lemurheavy/coveralls-public/issues/1721#issuecomment-1717308094) with our test results.

If you don't mind, I'm going to leave this PR open for the time being and may ask you to rebase once or twice after I make changes to the workflow to see if the changes have the desired effect. Will wait first for a response from the Coveralls team though.

I suspect that removing the [`github-token` input](https://github.com/PHPCSStandards/PHPCSUtils/blob/d79fda837cdb329b6de40956683f8fa67530ba3d/.github/workflows/test.yml#L356) will fix this, but that is completely counter to the Coveralls docs + counter to the info in the error message for the failed workflow....

**Comment by jrfnl** [comment]
Still for testing purposes, I've removed the Coveralls token now (PR #515). I suspect if you rebase, the build will pass.

(Note: I still won't merge the PR (yet), even when it does pass, as we may need to do more testing and having an open PR from a fork is useful for that)

**Comment by fredden** [comment]
:tada: all (required) checks passed!

**Comment by jrfnl** [comment]
@fredden Thanks for the rebase and happy to see it works!

I've done some extensive testing with a `private` repo now as well and written up my test outcomes. I'll wait for a reply from the Coveralls team, but if no more tests are needed, I'll merge this PR over the next few days.

Thanks for your help testing this!

**Comment by jrfnl** [comment]
@fredden I've finally got the go-ahead from Coveralls, so shouldn't need this PR anymore for further testing. Could you rebase the PR to get passed the merge conflict ? I'll merge it after that.

**Comment by fredden** [comment]
I've rebased this pull request. It looks like PHP 8.3 was already added to the list in duplicate in https://github.com/PHPCSStandards/PHPCSUtils/commit/64ee4aea8525a1aac9107ce939b90e819852439b

**Comment by jrfnl** [comment]
> I've rebased this pull request.

Thanks for the rebase. Not sure what you mean by ?
> It looks like PHP 8.3 was already added to the list in duplicate in [64ee4ae](https://github.com/PHPCSStandards/PHPCSUtils/commit/64ee4aea8525a1aac9107ce939b90e819852439b)

You mean in the badge ? Yes, that's 100% true. I updated the badge as the build is no longer allowed to fail. Sorry, I forgot that was included in this PR too. The badge ordering though was not yet done, so this PR should still be a valid change.

**Pull request merged**
