### PR TITLE
Use PSR-4 for autoloading classes

### PR DESCRIPTION
**Pull request by szepeviktor**
I hope it won't break anything! 😊

### CODE REVIEW

**Review by jrfnl — CHANGES_REQUESTED** [review]
Thanks for your willingness to contribute. I'd like to accept the change to the `autoload-dev`, but not the change to the `autoload`.

Under "normal" circumstances, the `autoload` from Composer will never be hit as the PHPCS autoloader takes precedent.

The `autoload` is only there for external PHPCS standards which have their own custom test suite. Also see the commit message of the commit adding it: https://github.com/PHPCSStandards/PHPCSUtils/pull/7/commits/bb0807336523540a49b2b393f27d734222d2b0b6

**Comment by szepeviktor** [comment]
All right. I run away 🐇

**Comment by jrfnl** [comment]
As I said, I'd be happy to accept the partial change, but closing this PR does not allow me to do so...

**Comment by szepeviktor** [comment]
Thank you.

**Pull request closed without merging**
